// Regression checks for the 2026-10-07 audit. Synthetic data in a disposable copy only.
const fs=require('node:fs'), os=require('node:os'), path=require('node:path'), crypto=require('node:crypto'), net=require('node:net');
const {spawn,execFileSync}=require('node:child_process');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'), copy=fs.mkdtempSync(path.join(os.tmpdir(),'perro-audit-fixes-'));
fs.cpSync(root,copy,{recursive:true,filter:p=>{const r=path.relative(root,p).split(path.sep).join('/');return !r.split('/').includes('.git')&&!r.startsWith('storage/data')&&!r.startsWith('storage/uploads/')&&!r.startsWith('storage/cache');}});
const php=process.env.PERRO_PHP_BIN||'php';
const gd=process.env.PERRO_PHP_GD_DIR?['-d','extension_dir='+process.env.PERRO_PHP_GD_DIR,'-d','extension=gd']:[];
let server,logs='',checks=0;
const check=(name,value)=>{assert.ok(value,name);checks++;console.log('PASS '+name);};
const read=n=>JSON.parse(fs.readFileSync(path.join(copy,'storage/data',n+'.json'),'utf8'));
const write=(n,v)=>fs.writeFileSync(path.join(copy,'storage/data',n+'.json'),JSON.stringify(v));
const token=h=>h.match(/name="csrf_token" value="([^"]+)"/)[1];
const revision=h=>h.match(/name="revision" value="([^"]+)"/)[1];
const includes="require 'includes/bootstrap.php';require 'includes/data.php';require 'includes/render.php';require 'includes/legal.php';require 'includes/moderation.php';require 'includes/experience.php';require 'includes/sharing.php';require 'includes/workflows.php';require 'includes/operations.php';";
const localPHP=code=>execFileSync(php,[...gd,'-r',includes+code],{cwd:copy,encoding:'utf8',windowsHide:true});
async function run(){
 const socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));
 const password=crypto.randomBytes(24).toString('hex'),base='http://127.0.0.1:'+port;
 server=spawn(php,[...gd,'-d','memory_limit=128M','-S','127.0.0.1:'+port,'router.php'],{cwd:copy,windowsHide:true,env:{...process.env,PERRO_ADMIN_PASSWORD_SHA256:crypto.createHash('sha256').update(password).digest('hex')}});
 server.stderr.on('data',b=>logs+=b.toString());
 function client(){const cookies=new Map();return async(route,fields,headers={})=>{const response=await fetch(base+route,{method:fields?'POST':'GET',body:fields?(fields instanceof FormData?fields:new URLSearchParams(fields)):undefined,redirect:'manual',headers:{...headers,cookie:[...cookies].map(([k,v])=>k+'='+v).join('; ')}});for(const c of response.headers.getSetCookie()){const [key,value]=c.split(';')[0].split('=');cookies.set(key,value);}return{status:response.status,html:await response.text(),headers:response.headers};};}
 const visitor=client(),admin=client();
 for(let i=0;i<50;i++){try{await visitor('/health');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 check('healthy storage produces minimal health response',(await visitor('/health')).html==='{"status":"ok"}');
 const phones=['0981 123 456','+595 981 123456','+595 0981 123 456','00595981123456','981123456','(0981) 123-4567','021 123 456','+54 9 11 1234 5678'];
 const numbers=JSON.parse(localPHP('echo json_encode(array_map("valid_whatsapp",'+JSON.stringify(phones).replace(/^\[/,'[')+'));'));
 check('phone normalization accepts five valid formats and rejects wrong length landline and foreign country',numbers.slice(0,5).every(n=>n==='595981123456')&&numbers.slice(5).every(n=>n===''));
 check('slugs consistently fold Spanish and Guarani accents',JSON.parse(localPHP('echo json_encode([slugify("Kuña"),slugify("José"),slugify("Pytã")]);')).join(',')==='kuna,jose,pyta');
 const now=new Date().toISOString(),future=new Date(Date.now()+60*86400000).toISOString();
 const template={id:'dog-seed-0',source_submission_id:'sub-seed-0',slug:'pyta-code00000',name:'Pytã',listing_type:'adoption',status:'published',adoption_status:'available',city:'Luque',department:'Central',age_group:'Cachorro',sex:'Macho',size:'Mediano',description:'Una historia sintética para probar las correcciones, sin datos reales.',photos:[],published_at:now,created_at:now,updated_at:now,last_confirmed_at:now,expires_at:future,contact_whatsapp:'',contact_name:'',public_name:false};
 const dogs=Array.from({length:500},(_,i)=>({...template,id:'dog-seed-'+i,source_submission_id:'sub-seed-'+i,slug:i?'perro-code'+String(i).padStart(5,'0'):template.slug,name:i?'Perro sintético '+i:template.name}));
 const subs=dogs.map((d,i)=>({...d,id:d.source_submission_id,status:'approved',published_dog_id:d.id,whatsapp:'595981'+String(i).padStart(6,'0'),reference:'REF'+String(i).padStart(5,'0'),submitter_name:'PRIVATE PERSON '+i,email:'person'+i+'@example.invalid',consents:{adult_confirm:true,authorized_confirm:true,photo_consent:true,no_sale_confirm:true,terms_version:'2026-10-05',privacy_version:'2026-10-05'},internal_note:'PRIVATE NOTE '+i,public_whatsapp:false}));
 write('dogs',dogs);write('submissions',subs);
 const login=await admin('/admin');await admin('/admin/login',{csrf_token:token(login.html),username:'admin',password});
 const before=performance.now(),panel=await admin('/admin?section=publicadas');const adminMs=performance.now()-before,csrf=token(panel.html);
 check('500-record admin renders under two seconds with 25 visible cards',panel.status===200&&adminMs<2000&&(panel.html.match(/class="admin-card"/g)||[]).length===25&&!panel.html.includes('id="solicitudes"'));
 const csvStart=performance.now(),csv=await admin('/admin/export.csv'),csvMs=performance.now()-csvStart;
 check('500-row CSV exports under two seconds and includes outcome columns',csv.status===200&&csvMs<2000&&csv.html.includes('Consultas (clics agregados)')&&csv.html.split('\n').length===502);
 const decodes=JSON.parse(localPHP('for($i=0;$i<500;$i++){find_record("dogs","dog-seed-".$i);public_dog_by_slug("perro-code".str_pad((string)$i,5,"0",STR_PAD_LEFT));}echo json_encode($GLOBALS["perro_dataset_reads"]);'));
 check('repeated listing and slug lookups decode dogs once',decodes.dogs===1);
 for(const q of [subs[0].reference,subs[0].submitter_name,'(0981) 000 000','code00000',subs[0].email]){
   const p=await admin('/admin?section=publicadas&q='+encodeURIComponent(q));check('admin unified search finds '+q,p.html.includes('Pytã')&&(p.html.match(/class="admin-card"/g)||[]).length===1);
 }
 check('submission search automatically includes all statuses',(await admin('/admin?q='+subs[0].reference)).html.includes('Pytã'));
 for(const q of ['pyta','cachorro','macho','code00000'])check('public search includes '+q,(await visitor('/perros?q='+q)).html.includes('Pytã'));
 check('partial department filter matches',(await visitor('/perros?department=cent')).html.includes('Pytã'));
 check('public code resolves regardless of listing category',(await visitor('/ficha/code00000')).headers.get('location')==='/perro/'+template.slug);
 const home=await visitor('/'),listing=await visitor('/perros');
 check('home and discovery do not start sessions and can be cached',!home.headers.get('set-cookie')&&!listing.headers.get('set-cookie')&&listing.headers.get('cache-control').includes('public'));
 check('home introduces lost and found notices',home.html.includes('Ver perdidos y encontrados')&&home.html.includes('¿Se perdió un perro o encontraste uno?'));
 check('path query cannot override URL route',(await visitor('/perros?path=admin')).html.includes('Perros para adoptar'));
 check('PHP version header is removed',!home.headers.get('x-powered-by'));
 check('login rotates CSRF token',token(login.html)!==csrf);
 check('empty organization page is noindex and absent from sitemap',(await visitor('/centros-de-adopcion')).html.includes('noindex,nofollow')&&!(await visitor('/sitemap.xml')).html.includes('centros-de-adopcion'));
 const preview=await visitor('/assets/images/default-preview.jpg');check('static default share image exists',preview.status===200&&preview.headers.get('content-type').includes('image/jpeg'));
 const first=await visitor('/perro/'+template.slug),click=await visitor('/contactar/'+template.slug),message=new URL(click.headers.get('location')).searchParams.get('text');
 check('enquiry identifies dog city code URL and adopter context',message.includes(template.slug)&&message.includes('code00000')&&message.includes('Luque')&&message.includes('Tipo de hogar:'));
 check('contact click stores only aggregate count',read('dogs')[0].contact_clicks===1&&!JSON.stringify(read('dogs')[0]).includes('127.0.0.1'));
 check('profile places safe adoption guidance by contact and has CSS mobile contact',first.html.includes('La adopción es gratuita: no pagues para reservar')&&first.html.includes('class="mobile-contact"'));
 const hintCases=JSON.parse(localPHP('$r=read_dataset("submissions")[0];$r["description"]="Solicito precio y seña para la venta. Contacto 0981 123 456.";$a=moderation_hints($r);$r["description"]="Un perro tranquilo que busca un hogar responsable.";echo json_encode([$a,moderation_hints($r)]);'));
 check('sale and public-phone hints flag review without rejecting clean text',hintCases[0].some(h=>h.includes('venta'))&&hintCases[0].some(h=>h.includes('teléfono'))&&hintCases[1].length===0);
 const imageSupport=localPHP('echo function_exists("imagecreatetruecolor")?"yes":"no";')==='yes';
 if(imageSupport){
  localPHP('$dir=PERRO_UPLOADS."/sub-seed-0";@mkdir($dir,0755,true);$im=imagecreatetruecolor(1600,900);imagefill($im,0,0,imagecolorallocate($im,20,90,100));imagejpeg($im,$dir."/fixture.jpg",90);imagedestroy($im);prepare_photo_variants($dir."/fixture.jpg");');
  const withPhoto=read('dogs');withPhoto[0].photos=['fixture.jpg'];write('dogs',withPhoto);
  const image=await visitor('/media/'+template.id+'/fixture.jpg?w=480');
  const conditional=await visitor('/media/'+template.id+'/fixture.jpg?w=480',undefined,{'if-none-match':image.headers.get('etag')});
  check('480px card variant stays under 120KB and a repeat request returns 304',image.status===200&&Number(image.headers.get('content-length'))<120000&&conditional.status===304);
  const dimensions=JSON.parse(localPHP('echo json_encode(getimagesize(PERRO_UPLOADS."/sub-seed-0/fixture.jpg.w480.jpg"));'));
  check('generated card photo is actually 480 pixels wide',dimensions[0]===480);
  await visitor('/compartir/'+template.slug+'/facebook.jpg');
  const cacheFiles=fs.readdirSync(path.join(copy,'storage/cache')),cacheMtimes=cacheFiles.map(n=>fs.statSync(path.join(copy,'storage/cache',n)).mtimeMs);
  await visitor('/compartir/'+template.slug+'/facebook.jpg');
  check('social image uses existing server cache on repeat request',cacheFiles.length===1&&cacheMtimes.every((t,i)=>fs.statSync(path.join(copy,'storage/cache',cacheFiles[i])).mtimeMs===t));
  withPhoto[0].status='removed';write('dogs',withPhoto);
  check('withdrawal revokes cached photo and social graphic at origin',(await visitor('/media/'+template.id+'/fixture.jpg?w=480',undefined,{'if-none-match':image.headers.get('etag')})).status===404&&(await visitor('/compartir/'+template.slug+'/facebook.jpg')).status===404);
  withPhoto[0].status='published';write('dogs',withPhoto);
 }
 const edit=await admin('/admin/edit?dataset=submissions&id='+subs[0].id);
 const fields={...subs[0],csrf_token:csrf,dataset:'submissions',id:subs[0].id,revision:revision(edit.html),review_confirm:'1',mixed_breed:'0',whatsapp:'+595 0981 123 456',city:'Areguá'};
 await admin('/admin/edit',fields);
 check('admin contact correction synchronizes consented public data without exposing private phone',read('submissions')[0].whatsapp==='595981123456'&&read('dogs')[0].city==='Areguá'&&read('dogs')[0].contact_whatsapp==='');
 check('contact correction is audited without logging phone or internal note',read('moderation').some(e=>e.action==='private_contact_corrected')&&!JSON.stringify(read('moderation')).includes('PRIVATE NOTE')&&!JSON.stringify(read('moderation')).includes('595981'));
 const conflict=await admin('/admin/edit',{...fields,city:'OLD CITY'}),second=await admin('/admin/edit',{...fields,revision:revision(conflict.html),city:'OLD CITY'});
 check('second save after conflict cannot overwrite current data',read('dogs')[0].city==='Areguá'&&second.html.includes('La ficha cambió en otra sesión'));
 const rejected={...subs[1],status:'pending'};write('submissions',[read('submissions')[0],rejected,...subs.slice(2)]);
 await admin('/admin/action',{csrf_token:csrf,dataset:'submissions',id:rejected.id,action:'reject'});
 check('empty rejection preserves note',read('submissions')[1].internal_note===rejected.internal_note);
 await admin('/admin/action',{csrf_token:csrf,dataset:'submissions',id:rejected.id,action:'reopen'});check('rejected submission can reopen',read('submissions')[1].status==='pending');
 const expired=read('dogs');expired[0].expires_at=new Date(Date.now()-86400000).toISOString();expired[1].adoption_status='reserved';expired[1].status_changed_at=new Date(Date.now()-15*86400000).toISOString();write('dogs',expired);
 const confirm=await admin('/admin?section=confirmar');check('worklist includes recent expiry and old reservation',confirm.html.includes('Pytã')&&confirm.html.includes('Perro sintético 1')&&confirm.html.includes('Ficha code00000'));
 check('admin expired state cannot claim available',(await admin('/admin?section=publicadas&q=code00000')).html.includes('>Vencida</span>'));
 await admin('/admin/action',{csrf_token:csrf,dataset:'dogs',id:template.id,action:'available',owner_confirmed:'1'});
 check('confirmed renewal removes expiry item',!(await admin('/admin?section=confirmar')).html.includes('<h3>Pytã</h3>'));
 const reportPage=await visitor('/perro/'+template.slug),reportToken=token(reportPage.html);
 const badReport=await visitor('/reportar',{csrf_token:reportToken,slug:template.slug,reason:'',category:'sale'});check('invalid report returns to its profile',badReport.headers.get('location')==='/perro/'+template.slug+'#reportar');
 await visitor('/reportar',{csrf_token:reportToken,slug:template.slug,reason:'Synthetic review request',category:'sale'});
 const report=read('reports')[0],reportPanel=await admin('/admin?section=reportes');
 check('reports have category date dog edit link and open badge',report.category==='sale'&&reportPanel.html.includes('dataset=dogs&amp;id='+template.id)&&reportPanel.html.includes('Venta, cobro o seña')&&(await admin('/admin?section=publicadas&q=code00000')).html.includes('reporte(s) abierto(s)'));
 await admin('/admin/action',{csrf_token:csrf,dataset:'reports',id:report.id,action:'resolve',note:'Verified synthetic resolution'});
 check('resolution records private note and date',read('reports')[0].resolution_note==='Verified synthetic resolution'&&!!read('reports')[0].resolved_at);
 const variants=['expires_at','last_confirmed_at','approximate_age','photos','contact_whatsapp'];
 const valid=read('dogs');
 for(const key of variants){const broken=structuredClone(valid);delete broken[0][key];write('dogs',broken);const page=await visitor('/perro/'+template.slug);check('missing '+key+' fails safely',key==='expires_at'?page.status===404:page.status===200);check('admin tolerates missing '+key,(await admin('/admin?section=publicadas')).status===200);}
 write('dogs',valid);
 const policy=JSON.parse(localPHP('$r=["consents"=>["adult_confirm"=>true,"authorized_confirm"=>true,"photo_consent"=>true,"no_sale_confirm"=>true,"terms_version"=>"2026-10-05","privacy_version"=>"2026-10-05"]];$a=policy_accepted($r);$r["consents"]["terms_version"]="unknown";echo json_encode([$a,policy_accepted($r)]);'));
 check('compatible historical consent survives editorial updates while unknown policy is rejected',policy[0]&&!policy[1]);
 check('IPv6 addresses in same /64 share rate identity',JSON.parse(localPHP('$_SERVER["REMOTE_ADDR"]="2001:db8:1:2::1";$a=rate_address();$_SERVER["REMOTE_ADDR"]="2001:db8:1:2::abcd";echo json_encode($a===rate_address());')));
 check('IPv4-mapped IPv6 preserves distinct IPv4 identities',JSON.parse(localPHP('$_SERVER["REMOTE_ADDR"]="::ffff:192.0.2.1";$a=rate_address();$_SERVER["REMOTE_ADDR"]="::ffff:192.0.2.2";echo json_encode([$a=== "192.0.2.1",$a!==rate_address()]);')).every(Boolean));
 const securityBefore=JSON.stringify(read('security')),form=await visitor('/dar-perro-en-adopcion');
 const formFields={csrf_token:token(form.html),form_started:String(Math.floor(Date.now()/1000)-10),listing_type:'adoption',submitter_name:'LOCAL RATE FIXTURE',whatsapp:'0981123456',relationship:'Responsable actual',name:'LOCAL RATE FIXTURE DOG',department:'Central',city:'Luque',age_group:'Cachorro',sex:'Macho',size:'Mediano',description:'Una historia de prueba suficientemente larga para validar archivos.',adult_confirm:'1',authorized_confirm:'1',photo_consent:'1',terms_accept:'1',no_sale_confirm:'1',terms_version:form.html.match(/name="terms_version" value="([^"]+)"/)[1],privacy_version:form.html.match(/name="privacy_version" value="([^"]+)"/)[1]};
 const failed=new FormData();for(const [k,v] of Object.entries(formFields))failed.append(k,v);failed.append('photos[]',new Blob(['invalid'],{type:'image/jpeg'}),'invalid.jpg');await visitor('/enviar-perro',failed);
 check('failed photo validation does not spend success quota',JSON.stringify(read('security'))===securityBefore);
 check('photo retry explicitly asks to select photos again',(await visitor('/dar-perro-en-adopcion')).html.includes('foto'));
 const notify=read('notifications');check('report queued a notification without personal data',notify.some(n=>n.event==='report')&&!JSON.stringify(notify).includes('PRIVATE PERSON'));
 check('failed notification sender leaves retryable events',JSON.parse(localPHP('echo json_encode(dispatch_notifications(static fn($s)=>false));'))===0&&read('notifications').some(n=>n.status==='pending'));
 check('notification retry is delayed instead of immediately re-sent',Number(localPHP('echo dispatch_notifications(static fn(string $body): bool => true);'))===0);
 localPHP('with_data_lock(static function(): void {$items=read_dataset("notifications");foreach($items as &$item)if($item["status"]==="pending")$item["retry_after"]=0;unset($item);commit_datasets(["notifications"=>$items]);});');
 check('notification sender test dispatches queued event',JSON.parse(localPHP('echo json_encode(dispatch_notifications(static fn($s)=>str_contains($s,"/admin")&&!str_contains($s,"PRIVATE")));'))>=1);
 const old=read('dogs');old[2].status='removed';old[2].updated_at='2020-01-01T00:00:00Z';old[2].expires_at='2020-01-01T00:00:00Z';write('dogs',old);
 const maintenance=args=>execFileSync(php,[...gd,'tools/maintenance.php',...args],{cwd:copy,encoding:'utf8',windowsHide:true});
 const phoneRecords=read('submissions'),phoneJson=fs.readFileSync(path.join(copy,'storage/data/submissions.json'),'utf8');phoneRecords[0].whatsapp='5950981123456';write('submissions',phoneRecords);
 const migration=JSON.parse(maintenance(['--audit-phones']));check('legacy phone audit identifies record without changing or printing contacts',migration.mode==='read-only'&&migration.contact_issues.some(r=>r.id===subs[0].id)&&!JSON.stringify(migration).includes('5950981123456')&&read('submissions')[0].whatsapp==='5950981123456');fs.writeFileSync(path.join(copy,'storage/data/submissions.json'),phoneJson);
 maintenance(['--archive']);check('archiving defaults to dry run',read('dogs').length===500);
 maintenance(['--archive','--apply']);check('closed records archive out of active files but remain searchable',read('dogs').length===499&&(await admin('/admin?section=archivo&q=REF00002')).html.includes('PRIVATE PERSON 2'));
 const backupDir=fs.mkdtempSync(path.join(os.tmpdir(),'perro-backup-drill-'));const backup=maintenance(['--backup-dir='+backupDir]).trim();
 const drill=fs.mkdtempSync(path.join(os.tmpdir(),'perro-restore-drill-'));
 const restore=execFileSync(php,['-r','$z=new ZipArchive();if($z->open($argv[1])!==true)exit(1);if(!$z->extractTo($argv[2]))exit(2);$z->close();echo count(json_decode(file_get_contents($argv[2]."/storage/data/dogs.json"),true));',backup,drill],{encoding:'utf8',windowsHide:true});
 check('backup restores to disposable copy with matching record count',Number(restore)===read('dogs').length);
 const deleted=read('submissions')[0];await admin('/admin/delete',{csrf_token:csrf,id:deleted.id,delete_confirm:'1'});
 const remaining=fs.readdirSync(path.join(copy,'storage/data')).filter(n=>n.endsWith('.json')).map(n=>fs.readFileSync(path.join(copy,'storage/data',n),'utf8')).join('\n');
 check('verified deletion removes linked public and private records notes and reports',!remaining.includes('PRIVATE PERSON 0')&&!remaining.includes('person0@example.invalid')&&!remaining.includes('PRIVATE NOTE 0')&&!remaining.includes('595981123456')&&!read('dogs').some(d=>d.id===template.id));
 fs.writeFileSync(path.join(copy,'storage/data/login-attempts.json'),'invalid');const recovery=client(),recoveryLogin=await recovery('/admin');await recovery('/admin/login',{csrf_token:token(recoveryLogin.html),username:'admin',password});
 check('corrupt login counters are preserved and access recovers',(await recovery('/admin')).html.includes('Moderación de Perro')&&fs.readdirSync(path.join(copy,'storage/data')).some(n=>n.startsWith('login-attempts.json.corrupt-')));
 for(let i=0;i<10;i++){const p=await recovery('/admin');await recovery('/admin/login',{csrf_token:token(p.html),username:'admin',password:'wrong'});}
 const blocked=await recovery('/admin');await recovery('/admin/login',{csrf_token:token(blocked.html),username:'admin',password});check('lockout explains retry time',(await recovery('/admin')).html.includes('Esperá 15 minutos'));
 const networkLock=JSON.parse(localPHP('$config["admin_password_sha256"]='+JSON.stringify(crypto.createHash('sha256').update(password).digest('hex'))+';$_SERVER["REMOTE_ADDR"]="192.0.2.44";echo json_encode([verify_admin_login("admin",'+JSON.stringify(password)+'),!empty($GLOBALS["perro_login_locked"])]);'));
 check('account lockout also applies from another network',networkLock[0]===false&&networkLock[1]===true);
 const healthy=fs.readFileSync(path.join(copy,'storage/data/dogs.json'));fs.writeFileSync(path.join(copy,'storage/data/dogs.json'),'broken');
 const unhealthy=await visitor('/health'),brokenHome=await visitor('/');
 check('corrupt storage returns clean traceable 503 health and single error document',unhealthy.status===503&&unhealthy.html==='{"status":"unavailable"}'&&brokenHome.status===503&&(brokenHome.html.match(/<!doctype html>/g)||[]).length===1&&!!brokenHome.headers.get('x-perro-incident'));
 fs.writeFileSync(path.join(copy,'storage/data/dogs.json'),healthy);
 check('logs identify corrupt dataset and omit personal records',logs.includes('archivo de registros: dogs')&&!logs.includes('PRIVATE PERSON'));
 console.log(JSON.stringify({checks,admin500Ms:Math.round(adminMs),csv500Ms:Math.round(csvMs),copy,restoreDrill:drill}));
}
run().catch(e=>{console.error(e.stack+'\nServer log:\n'+logs);process.exitCode=1;}).finally(()=>server?.kill());
