// Storage regressions use a disposable source copy and synthetic records only.
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),tmpRoot=process.env.PERRO_TEST_TMP_ROOT||os.tmpdir();
fs.mkdirSync(tmpRoot,{recursive:true});const temp=fs.mkdtempSync(path.join(tmpRoot,'perro-storage-')),copy=path.join(temp,'app');
fs.cpSync(root,copy,{recursive:true,filter:p=>!path.relative(root,p).split(path.sep).some(x=>['.git','storage'].includes(x))});
const php=process.env.PERRO_PHP_BIN||'php',names=['dogs','submissions','reports','moderation','settings','security','archive','notifications','owner_actions','cleanup'];
const data=path.join(copy,'storage/data'),uploads=path.join(copy,'storage/uploads');
const beacon=path.join(copy,'storage/installation.json');
const installation=()=>JSON.parse(fs.readFileSync(beacon,'utf8'));
const boot=`require __DIR__.'/includes/bootstrap.php'; require __DIR__.'/includes/data.php'; require __DIR__.'/includes/render.php'; require __DIR__.'/includes/legal.php'; require __DIR__.'/includes/moderation.php'; require __DIR__.'/includes/accounts.php'; require __DIR__.'/includes/sharing.php'; require __DIR__.'/includes/operations.php'; require __DIR__.'/includes/backups.php';`;
const standalone=`require __DIR__.'/includes/storage.php'; require __DIR__.'/includes/backups.php';`;
let checks=0,sequence=0,server,serverLogs='';const children=new Set();
const check=(label,value)=>{assert.ok(value,label);checks++;};
const read=name=>JSON.parse(fs.readFileSync(path.join(data,name+'.json'),'utf8'));
const write=(name,rows)=>fs.writeFileSync(path.join(data,name+'.json'),JSON.stringify(rows));
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
function snapshot(dir){const result={};if(!fs.existsSync(dir))return result;for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory()){for(const [key,value]of Object.entries(snapshot(file)))result[entry.name+'/'+key]=value;}else if(entry.isFile())result[entry.name]=hash(file);}return result;}
function child(args,options={}){return new Promise((resolve,reject)=>{const proc=spawn(php,args,{cwd:copy,windowsHide:true,env:{...process.env,PERRO_NOINDEX:'1',PERRO_TEST_INPUT:JSON.stringify(options.input||{})}});children.add(proc);let stdout='',stderr='';const timeout=setTimeout(()=>proc.kill(),60000);proc.stdout.on('data',b=>stdout+=b);proc.stderr.on('data',b=>stderr+=b);proc.once('error',e=>{clearTimeout(timeout);children.delete(proc);reject(e);});proc.once('exit',code=>{clearTimeout(timeout);children.delete(proc);resolve({code,stdout,stderr});});});}
function script(body,initialize=true){const file=path.join(copy,'storage-test-'+(++sequence)+'.php');fs.writeFileSync(file,`<?php ${initialize?boot:standalone} $input=json_decode(getenv('PERRO_TEST_INPUT'),true); ${body}`);return file;}
async function run(body,input={},initialize=true){const result=await child([script(body,initialize)],{input});if(result.code!==0)throw Error(result.stderr||'PHP helper failed: '+result.code);return result.stdout.trim();}
async function fresh(){fs.rmSync(path.join(copy,'storage'),{recursive:true,force:true});await run('echo "initialized";');}
async function start(){const socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));server=spawn(php,['-S','127.0.0.1:'+port,'router.php'],{cwd:copy,windowsHide:true,env:{...process.env,PERRO_NOINDEX:'1'}});server.stderr.on('data',b=>serverLogs+=b);server.once('error',e=>serverLogs+=e.message);const base='http://127.0.0.1:'+port;for(let i=0;i<300;i++){try{const response=await fetch(base+'/health');if(response.status===200)return base;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Preview unavailable: '+serverLogs);}
async function stop(){if(server&&server.exitCode===null)await new Promise(r=>{server.once('exit',r);server.kill();});server=null;}
const now='2026-01-01T12:00:00Z',dog={id:'synthetic-dog',slug:'synthetic-dog',name:'Synthetic dog',listing_type:'adoption',status:'published',adoption_status:'available',created_at:now,published_at:now,updated_at:now,last_confirmed_at:now,expires_at:'2099-01-01T00:00:00Z',city:'Luque',photos:[],contact_name:'SYNTHETIC_PRIVATE_OWNER',contact_whatsapp:'595991123456',internal_note:'SYNTHETIC_PRIVATE_NOTE'};
async function main(){
  await fresh();check('fresh initialization records schema 2',read('storage-state').schema_version===2);
  check('fresh installation creates all ten datasets',names.every(n=>Array.isArray(read(n))&&read(n).length===0));
  check('fresh installation records its installed beacon outside data',installation().phase==='installed'&&installation().schema_version===2);
  const installedBefore=snapshot(data);await run('echo "second boot";');check('repeat bootstrap preserves dataset bytes',JSON.stringify(installedBefore)===JSON.stringify(snapshot(data)));
  const originalStorage=fs.readFileSync(path.join(copy,'includes/storage.php'),'utf8');
  fs.rmSync(path.join(copy,'storage'),{recursive:true,force:true});
  const faultedStorage=originalStorage.replace(/return true;\r?\n}/,"if (basename($file) === 'dogs.json') exit(77); return true;\n}");
  assert.notEqual(faultedStorage,originalStorage,'initialization interruption injector found write boundary');fs.writeFileSync(path.join(copy,'includes/storage.php'),faultedStorage);
  const interrupted=await child([script('echo "should not finish";')]);fs.writeFileSync(path.join(copy,'includes/storage.php'),originalStorage);
  check('injected first-dataset interruption leaves an explicit initializing beacon',interrupted.code===77&&installation().phase==='initializing'&&read('dogs').length===0&&!fs.existsSync(path.join(data,'submissions.json')));
  const firstDatasetBytes=fs.readFileSync(path.join(data,'dogs.json'),'utf8');await run('echo "resumed";');
  check('empty interrupted initialization resumes to all ten empty datasets',installation().phase==='installed'&&names.every(n=>read(n).length===0));
  check('initialization resume preserves the already-written dataset bytes',fs.readFileSync(path.join(data,'dogs.json'),'utf8')===firstDatasetBytes);
  for(const withPhoto of [true,false]){
    await fresh();write('dogs',[dog]);const markerHash=hash(beacon);
    if(withPhoto){fs.mkdirSync(path.join(uploads,dog.id));fs.writeFileSync(path.join(uploads,dog.id,'synthetic.jpg'),'synthetic pixels');}
    fs.rmSync(data,{recursive:true});const lost=await child([script('echo "must fail";')]);
    check('lost entire established data directory fails closed '+withPhoto,lost.code!==0&&!fs.existsSync(data)&&hash(beacon)===markerHash);
    if(withPhoto)check('lost data directory never removes surviving photo',fs.readFileSync(path.join(uploads,dog.id,'synthetic.jpg'),'utf8')==='synthetic pixels');
  }
  await fresh();const innerStateBytes=fs.readFileSync(path.join(data,'storage-state.json'),'utf8');fs.unlinkSync(path.join(data,'storage-state.json'));
  const missingState=await child([script('echo "must fail";')]);check('installed beacon prevents recreating a missing inner state',missingState.code!==0&&!fs.existsSync(path.join(data,'storage-state.json')));fs.writeFileSync(path.join(data,'storage-state.json'),innerStateBytes);
  const markerBytes=fs.readFileSync(beacon,'utf8');for(const invalid of ['{broken',JSON.stringify({...installation(),phase:'unknown'})]){
    fs.writeFileSync(beacon,invalid);const invalidMarker=await child([script('echo "must fail";')]);check('corrupt or unknown installation beacon is never repaired',invalidMarker.code!==0&&fs.readFileSync(beacon,'utf8')===invalid);fs.writeFileSync(beacon,markerBytes);
  }
  fs.writeFileSync(beacon,JSON.stringify({...installation(),phase:'initializing'}));write('dogs',[dog]);const nonemptyResume=await child([script('echo "must fail";')]);check('initializing phase cannot fill/reset an installation with records',nonemptyResume.code!==0&&read('dogs')[0].id===dog.id&&installation().phase==='initializing');
  await fresh();fs.writeFileSync(beacon,JSON.stringify({...installation(),phase:'initializing'}));fs.writeFileSync(path.join(data,'unknown.json'),'[]');const unknownResume=await child([script('echo "must fail";')]);check('initialization resume rejects unknown storage paths',unknownResume.code!==0&&fs.existsSync(path.join(data,'unknown.json')));
  await fresh();fs.unlinkSync(beacon);fs.mkdirSync(path.join(uploads,'orphan'));fs.writeFileSync(path.join(uploads,'orphan','synthetic.jpg'),'surviving legacy fixture');fs.rmSync(data,{recursive:true});const orphaned=await child([script('echo "must fail";')]);check('unmarked surviving uploads never cause silent fresh initialization',orphaned.code!==0&&!fs.existsSync(path.join(data,'dogs.json')));
  fs.rmSync(path.join(copy,'storage'),{recursive:true,force:true});fs.mkdirSync(path.join(copy,'storage/cache'),{recursive:true});const cacheEvidence=await child([script('echo "must fail";')]);check('other surviving storage evidence never causes fresh reset',cacheEvidence.code!==0&&!fs.existsSync(path.join(data,'dogs.json')));
  await fresh();const legacySchemaBytes=snapshot(data);fs.unlinkSync(beacon);await run('echo "adopted schema 2";');check('complete pre-beacon schema 2 is adopted without dataset rewrites',installation().phase==='installed'&&JSON.stringify(legacySchemaBytes)===JSON.stringify(snapshot(data)));
  fs.rmSync(path.join(copy,'storage'),{recursive:true,force:true});fs.mkdirSync(data,{recursive:true});fs.mkdirSync(uploads,{recursive:true});
  const baseBytes={};for(const name of names.slice(0,8)){const rows=name==='dogs'?[dog]:name==='settings'?[{id:'settings',admin_password_sha256:'SYNTHETIC_ONLY_HASH',operator_name:'SYNTHETIC_PRIVATE_OPERATOR',custom:{retain:true}}]:[];baseBytes[name]=JSON.stringify(rows,null,3)+'\n';fs.writeFileSync(path.join(data,name+'.json'),baseBytes[name]);}
  await run('echo "adopted existing installation";');
  check('unversioned upgrade preserves all eight files byte for byte',names.slice(0,8).every(n=>fs.readFileSync(path.join(data,n+'.json'),'utf8')===baseBytes[n]));
  check('unversioned upgrade retains private settings and custom keys',read('settings')[0].custom.retain===true&&read('settings')[0].admin_password_sha256==='SYNTHETIC_ONLY_HASH');
  check('unversioned upgrade adds only new datasets and schema marker',read('storage-state').schema_version===2&&read('owner_actions').length===0&&read('cleanup').length===0);
  check('validated unversioned installation receives an installed beacon',installation().phase==='installed');
  let base=await start();fs.unlinkSync(path.join(data,'reports.json'));
  const missing=await fetch(base+'/health');check('missing established dataset fails health with 503',missing.status===503);check('missing dataset is never recreated as empty',!fs.existsSync(path.join(data,'reports.json')));
  write('reports',[]);write('dogs',[dog]);
  fs.writeFileSync(path.join(data,'dogs.json'),'{broken');let response=await fetch(base+'/health');check('malformed JSON fails health',response.status===503);check('malformed bytes survive failed request',fs.readFileSync(path.join(data,'dogs.json'),'utf8')==='{broken');
  write('dogs',[dog,{...dog,name:'duplicate'}]);response=await fetch(base+'/health');check('duplicate IDs fail health',response.status===503);check('duplicate records are not silently deduplicated',read('dogs').length===2);write('dogs',[dog]);await stop();
  const journal={reports:[{id:'journal-report',dog_id:dog.id,status:'open',created_at:now}]};fs.writeFileSync(path.join(data,'transaction.json'),JSON.stringify(journal));
  const beforeDoctor=snapshot(data),sourceBefore=snapshot(path.join(copy,'includes'));const diagnosis=await child(['tools/maintenance.php','--doctor']);const report=JSON.parse(diagnosis.stdout);
  check('doctor identifies pending journal without replay',diagnosis.code===2&&report.issues.some(i=>i.code==='pending_transaction'));
  check('doctor preserves every source dataset and pending journal hash',JSON.stringify(beforeDoctor)===JSON.stringify(snapshot(data)));
  check('doctor preserves PHP source hashes',JSON.stringify(sourceBefore)===JSON.stringify(snapshot(path.join(copy,'includes'))));
  check('doctor output excludes private field values',!['SYNTHETIC_PRIVATE_OWNER','SYNTHETIC_PRIVATE_NOTE','SYNTHETIC_ONLY_HASH','595991123456'].some(v=>(diagnosis.stdout+diagnosis.stderr).includes(v)));
  check('doctor does not execute pending transaction',read('reports').length===0);fs.unlinkSync(path.join(data,'transaction.json'));
  const absentSource=path.join(temp,'absent-source');fs.mkdirSync(absentSource);const emptyDoctor=JSON.parse(await run('echo json_encode(storage_doctor($input["root"]));',{root:absentSource},false));check('doctor never initializes a missing installation',!emptyDoctor.ok&&!fs.existsSync(path.join(absentSource,'storage')));
  const failed=await child([script(`unlink(PERRO_DATA.'/reports.json');mkdir(PERRO_DATA.'/reports.json');commit_datasets(['dogs'=>[$input['dog']],'reports'=>[['id'=>'recovered-report','dog_id'=>$input['dog']['id'],'status'=>'open','created_at'=>$input['dog']['created_at']]]]);`)],{input:{dog:{...dog,name:'Committed first replacement'}}});
  check('second dataset replacement failure is reported',failed.code!==0);check('partial commit retains recovery journal',fs.existsSync(path.join(data,'transaction.json')));check('first dataset replacement happened before injected failure',read('dogs')[0].name==='Committed first replacement');
  fs.rmdirSync(path.join(data,'reports.json'));await run('echo "recovered";');check('bootstrap replays remaining dataset from journal',read('reports')[0].id==='recovered-report');check('successful replay removes journal',!fs.existsSync(path.join(data,'transaction.json')));check('recovery retains first replacement',read('dogs')[0].name==='Committed first replacement');
  await fresh();write('notifications',Array.from({length:6},(_,i)=>({id:'notify-'+i,event:'report',reference:'SYNTHETIC-'+i,status:'pending',created_at:now})));
  const deliveryLog=path.join(temp,'synthetic-deliveries.jsonl'),go=path.join(temp,'go');
  const worker=script(`file_put_contents($input['ready'],'ready');while(!is_file($input['go']))usleep(10000);echo dispatch_notifications(static function(string $body)use($input):bool{usleep(100000);return file_put_contents($input['log'],json_encode(['body'=>$body])."\\n",FILE_APPEND|LOCK_EX)!==false;});`);
  const ready=[path.join(temp,'ready1'),path.join(temp,'ready2')];const workers=ready.map(file=>child([worker],{input:{ready:file,go,log:deliveryLog}}));
  for(let i=0;i<300&&!ready.every(file=>fs.existsSync(file));i++)await new Promise(r=>setTimeout(r,100));check('both notification workers reach concurrent barrier',ready.every(file=>fs.existsSync(file)));fs.writeFileSync(go,'go');const outcomes=await Promise.all(workers);
  check('concurrent workers complete successfully',outcomes.every(r=>r.code===0));const lines=fs.readFileSync(deliveryLog,'utf8').trim().split('\n').map(s=>JSON.parse(s));check('six queued alerts delivered exactly once across workers',lines.length===6&&new Set(lines.map(x=>x.body)).size===6);check('all concurrent alerts finish sent',read('notifications').every(n=>n.status==='sent'&&n.attempts===1));
  write('notifications',[{id:'lease-test',event:'report',reference:'LEASE',created_at:now,status:'pending'}]);
  const leases=JSON.parse(await run(`$first=claim_notification();$item=find_record('notifications',$first['id']);$item['lease_until']=time()-1;save_record('notifications',$item);$second=claim_notification();$stale=finish_notification($first,true);$middle=find_record('notifications',$first['id']);$current=finish_notification($second,true);echo json_encode(['different'=>$first['claim']!==$second['claim'],'stale'=>$stale,'middle'=>$middle['status'],'current'=>$current]);`));
  check('expired lease can be reclaimed with distinct token',leases.different);check('stale acknowledgement cannot consume a new lease',leases.stale===false&&leases.middle==='processing');check('current lease owner can finish',leases.current===true&&read('notifications')[0].status==='sent');
  write('notifications',[{id:'retry-test',event:'report',reference:'RETRY',created_at:now,status:'pending'}]);
  await run(`for($i=0;$i<5;$i++){dispatch_notifications(static fn(string $body):bool=>false);$item=find_record('notifications','retry-test');$item['retry_after']=0;save_record('notifications',$item);}echo json_encode(claim_notification());`);
  check('fifth transport failure exhausts retry budget',read('notifications')[0].status==='failed'&&read('notifications')[0].attempts===5);check('failed notification remains unclaimed',await run('echo json_encode(claim_notification());')==='null');
  await fresh();write('dogs',[dog]);write('reports',[{id:'delete-report',dog_id:dog.id,status:'open',created_at:now}]);write('owner_actions',[{id:'owner-link',dog_id:dog.id}]);
  const folder=path.join(uploads,dog.id),blocker=path.join(folder,'nested-blocker');fs.mkdirSync(blocker,{recursive:true});fs.writeFileSync(path.join(blocker,'synthetic.txt'),'fixture');fs.writeFileSync(path.join(folder,'synthetic.jpg'),'synthetic pixels');
  await run(`delete_listing_data('${dog.id}');echo "deleted records";`);check('deletion removes dog, linked report and owner token despite filesystem failure',read('dogs').length===0&&read('reports').length===0&&read('owner_actions').length===0);check('filesystem failure leaves durable pending cleanup',read('cleanup').length===1&&read('cleanup')[0].status==='pending'&&read('cleanup')[0].attempts===1);check('cleanup failure is visible without persisting exception details',read('cleanup')[0].error==='filesystem_cleanup_failed'&&fs.existsSync(blocker));
  fs.rmSync(blocker,{recursive:true});const cleaned=JSON.parse(await run('echo json_encode(run_cleanup_jobs());'));check('retry completes after blocker removal',cleaned.completed===1&&cleaned.pending===0&&!fs.existsSync(folder));check('completed cleanup removes deleted identifiers',!Object.hasOwn(read('cleanup')[0],'folders'));const again=JSON.parse(await run('echo json_encode(run_cleanup_jobs());'));check('completed cleanup is idempotent',again.completed===0&&again.failed===0&&read('cleanup')[0].attempts===2);
  const fairJobs=Array.from({length:21},(_,i)=>({id:'fair-'+i,folders:['fair-'+i],status:'pending',attempts:0}));
  for(let i=0;i<21;i++){fs.mkdirSync(path.join(uploads,'fair-'+i));if(i<20)fs.mkdirSync(path.join(uploads,'fair-'+i,'blocker'));}write('cleanup',fairJobs);
  const firstBatch=JSON.parse(await run('echo json_encode(run_cleanup_jobs());'));check('twenty blocked cleanup attempts remain retryable',firstBatch.failed===20&&firstBatch.completed===0&&firstBatch.pending===21);
  check('failed cleanup jobs yield to unattempted later job',read('cleanup')[0].id==='fair-20');
  const secondBatch=JSON.parse(await run('echo json_encode(run_cleanup_jobs());'));check('later deletable folder is removed despite twenty earlier blockers',secondBatch.completed===1&&!fs.existsSync(path.join(uploads,'fair-20'))&&read('cleanup').find(j=>j.id==='fair-20').attempts===1);
  for(let i=0;i<20;i++)fs.rmdirSync(path.join(uploads,'fair-'+i,'blocker'));const retriedBatch=JSON.parse(await run('echo json_encode(run_cleanup_jobs(50));'));check('rotated failed cleanup jobs succeed after blockers clear',retriedBatch.completed===20&&retriedBatch.pending===0);
  await fresh();const archivedDog={...dog,status:'removed',expires_at:now};write('archive',[{id:'archive-dogs-'+dog.id,dataset:'dogs',record:archivedDog,archived_at:now}]);write('reports',[{id:'unresolved-report',dog_id:dog.id,status:'open',created_at:now}]);write('owner_actions',[{id:'old-owner-link',dog_id:dog.id}]);
  const archivedDoctor=await child(['tools/maintenance.php','--doctor']);check('archived dog remains valid target of unresolved report and owner link',archivedDoctor.code===0&&JSON.parse(archivedDoctor.stdout).ok);
  const backupDir=path.join(temp,'backups'),backup=await run('echo create_storage_backup($input["directory"]);',{directory:backupDir});check('backup produces ZIP and external checksum',fs.existsSync(backup)&&fs.existsSync(backup+'.sha256'));check('external checksum matches backup bytes',fs.readFileSync(backup+'.sha256','utf8').trim()===hash(backup));
  const manifest=JSON.parse(await run(`$zip=new ZipArchive();$zip->open($input['zip']);echo $zip->getFromName('storage-manifest.json');$zip->close();`,{zip:backup}));check('manifest contains exact dataset counts',names.every(n=>manifest.counts[n]===read(n).length));check('manifest file hashes match source storage',Object.entries(manifest.files).every(([name,entry])=>hash(path.join(copy,name))===entry.sha256));check('backup excludes lock/cache/temp artifacts',Object.keys(manifest.files).every(n=>!n.endsWith('.lock')&&!n.includes('/cache/')&&!n.includes('.tmp-')));
  check('backup manifest hashes the external installed beacon',Boolean(manifest.files['storage/installation.json'])&&manifest.files['storage/installation.json'].sha256===hash(beacon));
  const restore=path.join(temp,'restore'),sourceSnapshot=snapshot(data);const verified=await child(['tools/maintenance.php','--verify-backup='+backup,'--restore-dir='+restore]);check('standalone restore verifier accepts backup with archived report reference',verified.code===0&&JSON.parse(verified.stdout).ok);check('restore verifier reports source counts faithfully',JSON.stringify(JSON.parse(verified.stdout).counts)===JSON.stringify(manifest.counts));check('restore verifier preserves source storage',JSON.stringify(sourceSnapshot)===JSON.stringify(snapshot(data)));check('isolated restore does not initialize a lock or execute bootstrap',!fs.existsSync(path.join(restore,'storage/data/application.lock')));
  check('empty-photo backup verification restores required uploads directory',fs.statSync(path.join(restore,'storage/uploads')).isDirectory());
  const restoreStartup=await run(`define('PERRO_ROOT',$input['root']);define('PERRO_STORAGE',PERRO_ROOT.'/storage');define('PERRO_DATA',PERRO_STORAGE.'/data');define('PERRO_UPLOADS',PERRO_STORAGE.'/uploads');storage_prepare();echo 'started';`,{root:restore},false);check('empty-photo verified restore can start without filling missing datasets',restoreStartup==='started'&&JSON.parse(fs.readFileSync(path.join(restore,'storage/installation.json'),'utf8')).phase==='installed');
  const legacyBackup=path.join(temp,'legacy-schema2.zip');fs.copyFileSync(backup,legacyBackup);await run(`$zip=new ZipArchive();$zip->open($input['zip']);$manifest=json_decode($zip->getFromName('storage-manifest.json'),true);$zip->deleteName('storage/installation.json');unset($manifest['files']['storage/installation.json']);$zip->addFromString('storage-manifest.json',json_encode($manifest));$zip->close();`,{zip:legacyBackup});
  const legacyRestore=path.join(temp,'legacy-restore'),legacyVerified=await child(['tools/maintenance.php','--verify-backup='+legacyBackup,'--restore-dir='+legacyRestore]);check('complete schema 2 backup without beacon retains restore compatibility',legacyVerified.code===0&&JSON.parse(legacyVerified.stdout).ok&&!fs.existsSync(path.join(legacyRestore,'storage/installation.json')));
  const tampered=path.join(temp,'tampered.zip');fs.copyFileSync(backup,tampered);await run(`$zip=new ZipArchive();$zip->open($input['zip']);$zip->addFromString('storage/data/reports.json','[]');$zip->close();`,{zip:tampered});const rejected=await child(['tools/maintenance.php','--verify-backup='+tampered,'--restore-dir='+path.join(temp,'bad-restore')]);check('modified ZIP content fails manifest validation',rejected.code!==0);
  const traversal=path.join(temp,'traversal.zip');fs.copyFileSync(backup,traversal);await run(`$zip=new ZipArchive();$zip->open($input['zip']);$zip->addFromString('storage/../../escaped.txt','escape');$zip->close();`,{zip:traversal});const traversalResult=await child(['tools/maintenance.php','--verify-backup='+traversal,'--restore-dir='+path.join(temp,'traversal-restore')]);check('ZIP traversal fails before extraction',traversalResult.code!==0&&!fs.existsSync(path.join(temp,'escaped.txt')));
  const occupied=path.join(temp,'occupied');fs.mkdirSync(occupied);fs.writeFileSync(path.join(occupied,'keep.txt'),'keep');const nonempty=await child(['tools/maintenance.php','--verify-backup='+backup,'--restore-dir='+occupied]);check('nonempty destination rejected without changing its contents',nonempty.code!==0&&fs.readFileSync(path.join(occupied,'keep.txt'),'utf8')==='keep');const sourceTarget=path.join(copy,'forbidden-restore');const sourceRejected=await child(['tools/maintenance.php','--verify-backup='+backup,'--restore-dir='+sourceTarget]);check('restore into live source installation is rejected',sourceRejected.code!==0&&!fs.existsSync(path.join(sourceTarget,'storage')));check('rejected source descendant is never created',!fs.existsSync(sourceTarget));
  const originalReports=fs.readFileSync(path.join(data,'reports.json')),backupBefore=snapshot(backupDir);fs.writeFileSync(path.join(data,'reports.json'),'{corrupted synthetic source');
  const failedBackup=await run(`try{create_storage_backup($input['directory']);echo 'unexpected_success';}catch(Throwable $error){echo 'rejected';}`,{directory:backupDir});check('backup rejects a corrupt source dataset',failedBackup==='rejected');check('failed backup leaves no partial ZIP or checksum',JSON.stringify(backupBefore)===JSON.stringify(snapshot(backupDir)));fs.writeFileSync(path.join(data,'reports.json'),originalReports);
  const bootMarker=path.join(copy,'includes/bootstrap.php');fs.appendFileSync(bootMarker,`\nthrow new RuntimeException('synthetic bootstrap must not execute');\n`);const independent=await child(['tools/maintenance.php','--verify-backup='+backup,'--restore-dir='+path.join(temp,'independent-restore')]);check('verification remains independent of broken source bootstrap',independent.code===0&&JSON.parse(independent.stdout).ok);
  console.log(JSON.stringify({status:'passed',checks,scope:'isolated synthetic storage, workers and restore only'}));
}
main().catch(e=>{console.error(e.stack);console.error(serverLogs.slice(-2000));process.exitCode=1;}).finally(async()=>{await stop();await Promise.all([...children].map(proc=>new Promise(r=>{proc.once('exit',r);proc.kill();})));fs.rmSync(temp,{recursive:true,force:true});});
